### ISSUE TITLE
How to use ember-cli-dotenv with ember-cli-deploy?

### ISSUE THREAD

**Issue by kcollignon** [ember-cli/ember-cli-deploy#77]
I'm using the ember-cli-dotenv package. Has anyone had any luck with including environment variables in to the deploy.js file?

i've tried everything from `process.env.S3_SECRET_KEY` to `ENV.APP['S3_SECRET_KEY`]`

**Comment by ryanto** [comment]
`process.env` will have all your environment variables. 

From the command line you can run: `node -e "console.log(process.env)"` to see what's available.

**Comment by kcollignon** [comment]
Thanks @ryanto for that node command. That has helped me verify that my environment variables aren't being injected in the process env. 

Do you see anything that I might be missing?

Part of environment.js:
```javascript
module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'keying-instructions',
    environment: environment,
    baseURL: '/',
    locationType: 'hash',
    contentSecurityPolicy: {
      'default-src': "*",
      'script-src': "*", 
      'font-src': "*",
      'connect-src': "*", // Allow data (ajax/websocket)
      'img-src': "'*'",
      'style-src': "* 'unsafe-inline'", // Allow inline styles and loaded CSS from http://fonts.googleapis.com
      'media-src': "*"
    },
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      }
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
      S3_ACCESS_KEY: process.env.S3_ACCESS_KEY,
      S3_SECRET_KEY: process.env.S3_SECRET_KEY
    }
  };
```
Part of Brocfile:
```javascript
var app = new EmberApp({
  fingerprint: {
    prepend: 'https://s3.amazonaws.com/mybucket/images'
  },
  dotEnv: {
    clientAllowedKeys: ['S3_ACCESS_KEY', 'S3_SECRET_KEY']
  }
});

**Comment by lukemelia** [comment]
Sounds like we need to look at how ember-cli-dot-env works. Maybe we need to make sure we load after that addon?

**Comment by kcollignon** [comment]
Just for fun, I tried setting the deploy config to something random, but that was in my environment variables to see if it was getting loaded in, and it appeared it did. I received the error `uploadedFilePath is not defined` which I usually get when it just doesn't authenticate, but seemed to prove it was at least having access to process.env

**Comment by MattNguyen** [comment]
I'm also in need of having a solution to this.

I tried specifying the load-order, but that didn't see to work. 

I tried poking around and stuck some console logs in lib/commands/deploy.js and lib/tasks/assets.js to see if my .env vars  appear in process.env (https://github.com/MattNguyen/ember-cli-deploy/commit/001db4531fde35512587b0dc2df50ddfe8c0e139). The former does not contain my env vars, but the latter does, which is puzzling. Why would this happen?

**Comment by rockwood** [comment]
ember-cli-dotenv doesn't get loaded during the ember deploy process so environment variables from .env won't be available. I got around this by installing [dotenv](https://www.npmjs.com/package/dotenv) and adding this to my config.js:

```javascript
require('dotenv').load();
```

A better solution would be nice, but this works for now

**Comment by MattNguyen** [comment]
@rockwood, I'm not entirely sure if it's true that ember-cli-dotenv *doesn't* get loaded at all. The console.logs that I mentioned above seemed to show that the .env var gets loaded during the asset task. 

Your solution definitely works, but it's still unclear to me why .env vars are loaded some of the times.

**Comment by lukemelia** [comment]
Happy to accept a PR if you can figure out what's going on and we can support ember-cli-dot-env unobtrusively.

**Comment by achambers** [comment]
I'm pretty sure I came across this at some stage and it was due to the load
order of the addons.  Can't quite remember the specifics or how I fixed it
off the top of my head right now but let me have a dig around and see if I
can remember.

**Comment by danshultz** [comment]
For anyone looking to try and address this issue with the loading order of dotenv, I think the solution may lay in using the `after` or `before` hooks in the `ember-addon` section of the package.json.

http://www.ember-cli.com/#configuring-your-ember-addon-properties

Something along the lines of this may address the issue with dotenv

package.json
```json
...
"ember-addon": {
  "after": "ember-cli-dotenv"
}
...
```

**Comment by achambers** [comment]
Yep. That sounds familiar mate. I think that's a good shout.

**Comment by MattNguyen** [comment]
I tried placing ember-cli-dotenv in the after hook (https://github.com/MattNguyen/ember-cli-deploy/commit/353d709cdb9108cd6ea93d68a07160efe17ab31e), but it didn't fix the issue. Has anyone had success defining the load order?

**Comment by achambers** [comment]
According to the docs (http://www.ember-cli.com/#configuring-your-ember-addon-properties) it should be an `array`:

```javascript
"ember-addon": {
  // addon configuration properties
  "configPath": "tests/dummy/config",
  "before": "single-addon",
  "defaultBlueprint": "blueprint-that-isnt-package-name",
  "after": [
    "ember-cli-dotenv"
  ]
}
```

**Comment by achambers** [comment]
Sorry my bad....I didn't read the whole thing...It can take a string :S

**Comment by timrwilliams** [comment]
Can somebody provide a idiot's summary of what the current workaround is? Tried to piece it together from this thread but still not got it working. Thanks!

**Comment by LevelbossMike** [comment]
@timrwilliams You should be able to use dotenv directly because config.js is a javascript file where you can basically do anything you like.

**Comment by sheldonnbbaker** [comment]
I've also been unable to get this to work. I tried [adding `after` in ember-addon in package.json](https://github.com/MattNguyen/ember-cli-deploy/commit/353d709cdb9108cd6ea93d68a07160efe17ab31e), but my env vars still aren't picked up.

Does anyone have any other tips to share?

**Comment by achambers** [comment]
@sheldonnbbaker This is handled by default in 0.5.0. The beta.2 is currently available, otherwise maybe consider waiting until 0.5.0 is released which shouldn't be far away.

**Comment by masciugo** [comment]
@achambers If I am not using *ember-cli-dotenv* badly (i.e. populating my *.env* and try to call `process.env.MYSECRET` in my *deploy.rb*) with the following versions:

    "ember-cli-deploy": "0.5.0-beta.2",
    "ember-cli-deploy-lightning-pack": "0.2.0-beta.5",
    "ember-cli-dotenv": "^1.0.3",

my *.env* vars are still blank.

**Comment by achambers** [comment]
You don't need to install ember-cli-dot env. Remove that addon and add a file called `.env.deploy.<deploy-target>` to your project.

**Comment by masciugo** [comment]
I did try but still getting:

    |    - Missing config: `uploadClient`, using default: `[Function]`
    |    - Missing config: `s3Client`, using default: `[Function]`
    |    - Missing required config: `accessKeyId`
    |
    +- didFail
    Error: Missing required config: `accessKeyId`
    Error: Missing required config: `accessKeyId`
        at Class.CoreObject.extend.ensureConfigPropertySet (/Users/masciugo/dev/quenta/node_modules/ember-cli-deploy-lightning-pack/node_modules/ember-cli-deploy-s3/node_modules/ember-cli-deploy-plugin/index.js:41:13)
        at Array.forEach (native)
        at Class.CoreObject.extend.configure (/Users/masciugo/dev/quenta/node_modules/ember-cli-deploy-lightning-pack/node_modules/ember-cli-deploy-s3/node_modules/ember-cli-deploy-plugin/index.js:23:19)
        at Object._pipeline.register.fn (/Users/masciugo/dev/quenta/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:163:21)
        at Pipeline._notifyPipelinePluginHookExecution (/Users/masciugo/dev/quenta/node_modules/ember-cli-deploy/lib/models/pipeline.js:123:19)
        at lib$rsvp$$internal$$tryCatch (/Users/masciugo/dev/quenta/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
        at lib$rsvp$$internal$$invokeCallback (/Users/masciugo/dev/quenta/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
        at lib$rsvp$$internal$$publish (/Users/masciugo/dev/quenta/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
        at lib$rsvp$asap$$flush (/Users/masciugo/dev/quenta/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
        at process._tickCallback (node.js:355:11)|
    Pipeline aborted

sorry but I couldn't find any doc or note about this. I put my `.env.deploy.production` in my project root folder in the format

    MY_VAR_FOO=foo
    MY_VAR_BAR=bar

and try to access them with `process.env.MY_VAR_FOO` as I used to do with *ember-cli-dotenv*

**Comment by achambers** [comment]
Can you post the command you were using to run ember-cli-deploy please?

**Comment by masciugo** [comment]
ok.. I used production instead of prod. Sorry, still not habit. thank you

**Comment by achambers** [comment]
No probs. I'm closing this issue as `.env` support is baked in to 0.5.0
